name: Python CI

on:
  push:
  pull_request:
    branches: [ master ]
env:
  POETRY_VIRTUALENVS_CREATE: false

jobs:
  build:
    runs-on: ubuntu-16.04

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7

    - name: Install dependencies
      run: |
        pip install poetry
        poetry install

    - name: Run linters
      run: make lint

    - name: Run test
      run: make test

    - name: Coverage
      run: make coverage


    # CD part
    # - name: Push dags to GCS
    #   not implemented yet
